<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>WT.B2C.API.BuildingBlocks</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Http" Version="8.1.0" />
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="MaxMind.GeoIP2" Version="5.4.1" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.22" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.22" />
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.22" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
        <PackageReference Include="Refit.HttpClientFactory" Version="8.0.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
        <PackageReference Include="StackExchange.Redis" Version="2.10.1" />
        <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.1" />
    </ItemGroup>

</Project>
